apiVersion: v1
kind: Service
metadata:
    labels:
        app: polyscale-metrics-service
    name: polyscale-metrics-service
spec:
    ports:
    - name: 80-8080
      port: 80
      protocol: TCP
      targetPort: 2112
    selector:
        app: polyscale-metrics
    sessionAffinity: None
    type: ClusterIP
status:
    loadBalancer: {}